Add more info about file
kodi-czsk/plugin.video.sosac.ph pull request #109
Opened 2017-01-12 19:44 UTC by Saljack

Pridal jsem nacitani vice infa z JSONu jako je rok, rating, seria a epizoda.

2017-01-12 21:39 UTC, lzoubek approved these changes

2017-01-12 21:40 UTC, lzoubek commented on resources/lib/sosac.py
> +                    item['episode'] = int(episode_key)
Mohl by jsi fixnout i [sutils.py](https://github.com/kodi-czsk/plugin.video.sosac.ph/blob/json-rewrite/resources/lib/sutils.py#L209) ? Zbytecne tam parsujem regexem cislo serie a epizody

2017-01-12 22:08 UTC, Saljack commented on resources/lib/sosac.py
> +                    item['episode'] = int(episode_key)
Opraveno doufam, ze to je to co jsi myslel.

2017-01-12 22:11 UTC, Saljack commented
Jeste me napada jestli se nezbavit toho roku u filmu, kdyz je v info (v Kodi 17 se mi zobrazuje pred filmem). Dalsi napad je pridat do plotu (popisek) k filmum aspon genre toho filmu a mozna ty url na CSFD resp IMDB ale nevim, jestli k necomu jsou zda se na to da kliknout nebo tak neco.

2017-01-13 00:08 UTC, lzoubek commented on resources/lib/sosac.py
> +                    item['episode'] = int(episode_key)
diky!

2017-01-13 21:42 UTC, lubo requested changes

2017-01-13 21:42 UTC, Lubo commented on resources/lib/sutils.py
> +                epname = "S%02dE%02d.strm" % (itm['season'], itm['episode'])
Preco raz pouzivas `.format()` a raz `%` ? A preco v riadku 213 nepouzijes prostu concatenation (+) ?

2017-01-15 16:04 UTC, Saljack commented on resources/lib/sutils.py
> +                epname = "S%02dE%02d.strm" % (itm['season'], itm['episode'])
Opraveno na concatenation

2017-01-15 16:18 UTC, Saljack commented
Pridal jsem jeste:
- genre do plotu u filmu a 
- serialy rady a epizody jsou nyni na dve mista vypada to lepe
- u TV Shows - Recently added dvojtecku mezi nazev serialu a cislem rady

2017-01-16 21:27 UTC, merged