Several cosmetic improvements
kodi-czsk/plugin.video.sosac.ph pull request #122
Opened 2017-02-02 13:53 UTC by ToKroCZ

Updated changelog.txt and version in addon.xml, higher resolution of new icon and "fix" for #121.

2017-02-02 14:56 UTC, lzoubek commented
Diky za upravy, mergnu to po update resolveru

2017-02-02 15:40 UTC, lubo requested changes
Ikonka uz bola zmenena v predchodzom PR, preco je to tu ?!

2017-02-02 15:42 UTC, ToKroCZ commented
@Lubo Byla 256×256px, zjistil jsem, že může být i 512×512px. řekl jsem si, že když děláme novou, tak ji uděláme rovnou kvalitnější. 4K televize jsou stále častější a tam to má smysl. Btw psal jsem ti na FB, ale už nic, našel jsem si to ;-).

2017-02-02 15:45 UTC, lubo requested changes
Nerozumiem commitu 7fa1558. Je dobra praktika commitovat podla moznosti tak, aby bola vec v kazdom bode pouzitelna. Zbav sa toho commitu, prosim.

2017-02-02 15:45 UTC, Lubo commented on addon.xml
> +<addon id="plugin.video.sosac.ph" name="Sosáč" provider-name="L. Zoubek + jondas" version="1.3.1">
Nebumpuj verziu v PR. Co ak sa vyda tato verzia este predtym, nez sa mergne tvoj PR ?

2017-02-02 15:47 UTC, Lubo commented
@ToKroCZ Sorry, nevsimol som si. Bal som sa, ze vyslo nieco zle. Btw, prosim, nepis mi ohladom tejto komunity na moje sukromne ucty na ostatnych socialnych platformach. Nebudem na to reagovat.

2017-02-02 15:56 UTC, ToKroCZ commented
@Lubo Verzi jsem vrátil na 1.3.0, sorry. Mám to změnit i v changelogu?  7fa1558 je prostě odstranění staré ikonky, jak se toho mám zbavit? Sorry, nechtěl jsem otravovat, ale nevěděl jsem, jak jinak napsat, vzhledem k tomu, že tu nejsou soukromé zprávy ani nic podobného. 
Nikdy jsem doplňky nedělal, tak jsem se koukal na wiki a dělal jsem to podle instrukcí. Nedošlo mi, že ta verze je blbost.

2017-02-02 22:06 UTC, lzoubek commented
Z toho commitu si nic nedelej, vyslednej PR bude nejlepsi stejne squashnout (vyleze z toho nakonec jen 1 commit). 

Jinak toho commitu se zbavis prave pomoci squashe (je to trochu netrivialni metoda prace s commity)

2017-02-02 22:07 UTC, merged

2017-02-03 07:53 UTC, ToKroCZ commented
@lzoubek Díky moc za info! GitHub moc neznám, to by mě nenapadlo.