Polozka last update
kodi-czsk/plugin.video.sosac.ph pull request #126
Opened 2017-02-06 11:37 UTC by Saljack

Pridava last update polozku do uvodniho seznamu.

2017-02-10 14:51 UTC, co5mo commented
neviem ci je to mozne ale pridat polozku nove CZ stopy to nejde? je to dakde v JSONE? bolo by to fajn ked prida sosac cz dabing

dakujem

2017-02-11 13:56 UTC, Lubo commented
Popravde, nevyzera to celkom dobre, ked na to polozku kliknes a sosac vyhodi error. Tiez nedava zmysel, aby to vobec bola samostatna polozka. Co tak radsej dat ku kazdej kategorii do zatvorky tento cas ?

2017-02-11 13:57 UTC, lubo requested changes
Popravde, nevyzera to celkom dobre, ked na to polozku kliknes a sosac vyhodi error. Tiez nedava zmysel, aby to vobec bola samostatna polozka. Co tak radsej dat ku kazdej kategorii do zatvorky tento cas ?

2017-02-11 13:57 UTC, Lubo commented on resources/lib/sosac.py
> +        if lastmod is not None:
Tu staci `if lastmod:`.

2017-02-11 13:59 UTC, Saljack commented
Super napad nevedel jsem moc kam jinam to dat a vim, ze podobne info maji i jine pluginy takhle za ty polozky by to bylo asi lepsi.

2017-02-11 21:48 UTC, Lubo commented
Takze, prerobis to ?

2017-02-11 22:05 UTC, Saljack commented
Ano zítra na to mrknu 😉

2017-02-12 09:53 UTC, Saljack commented
Ok pridal jsem lastmod za Recently added polozky jinde to moc nedava smysl.

2017-02-12 10:08 UTC, lubo approved these changes

2017-02-12 10:09 UTC, merged