Oprava generovani NFO
kodi-czsk/plugin.video.sosac.ph pull request #129
Opened 2017-02-08 18:41 UTC by ExSport

- odstranuje zavislost na bbaron.sk domene
- oprava generovani CSFD/IMDB linku pokud neexistoval THETVDB link
- NFO file se negeneruje pokud neexistuje zadny link
- pokud je ID nevalidni, link se nevytvari
- vylepseno hledani spravneho linku pro THETVDB

2017-02-08 19:17 UTC, lubo requested changes
Celkovo nie som spokojny s kvalitou, prepis to prosim.

2017-02-08 19:17 UTC, lubo commented on resources/lib/sutils.py
> +                    id + '&language=all'))
Preco je `util.request()` v zatvorke ? Nevidim na to dovod.

2017-02-08 19:17 UTC, lubo commented on resources/lib/sutils.py
> +                tvid = re.search('<id>(\d+)</id>', data).group(1)
Prosim, povedz, ze sa tu nesnazis parsovat XML regexom...

2017-02-08 19:17 UTC, Lubo commented on resources/lib/sutils.py
>                  tvid = None
Tu urcite nechces odchytavat kazdu moznu exception. Navise, preco sa tomu nevyhnes napr. takto ?

```
tvid = re.search(...)
if tvid:
    return tvid.group(1)
```

Potom by si nemusel mat o riadok nizssie `if tvid is None:`, ktory vies mimochodom skratit na `if not tvid:`.

2017-02-08 19:17 UTC, Lubo commented on resources/lib/sutils.py
> +                    urllib.urlencode({'seriesname': name})+'&language=all'])
Tu by bolo korektnejsie enkodovat aj `language`. Navyse, zatvorka nie je potrebna.

2017-02-08 19:17 UTC, Lubo commented on resources/lib/sutils.py
> +                    tvid = None
Znova tie iste problemy ako vyssie...

2017-02-08 19:17 UTC, Lubo commented on resources/lib/sutils.py
> +                        re.match('^$|^[?0]$', params['imdb']) is None):
Nepotrebna zatvorka, `is not None` nie je potrebne pisat a `re.match('^$|^[?0]$', params['imdb']) is None` vies nahradit za `not re.match('^$|^[?0]$', params['imdb'])`.

2017-02-08 19:17 UTC, Lubo commented on resources/lib/sutils.py
> +                        re.match('^$|^[?0]$', params['csfd']) is None):
Rovnako ako vyssie...

2017-02-08 19:17 UTC, Lubo commented on resources/lib/sutils.py
> +                        re.match('^$|^[?0]$', params['imdb']) is None):
Rovnako ako vyssie...

2017-02-08 19:17 UTC, Lubo commented on resources/lib/sutils.py
> +                        re.match('^$|^[?0]$', params['csfd']) is None):
Rovnako ako vyssie...

2017-02-08 19:47 UTC, ExSport commented on resources/lib/sutils.py
> +                    id + '&language=all'))
Kvůli rozepsání na více řádků, kdy jsem se dočetl, že best practice je to dát celé do závorky jako jeden logický blok.
A je preferováno např. místo ukončení řádku lomitky.
Klidně je ale odstraním pokud beautifier nebude pak řvát.

2017-02-08 19:51 UTC, ExSport commented on resources/lib/sutils.py
> +                tvid = re.search('<id>(\d+)</id>', data).group(1)
Nevymýšlím nový kód. Podívej se do původního kódu kde to tak je, případně jsem proto využil stejný styl programování...Nejsem pythonista, tak když poradíš jak to udělat lépe, sem s tím.

2017-02-08 19:55 UTC, ExSport commented on resources/lib/sutils.py
>                  tvid = None
Netuším zda exception se generuje kvůli groupovani null objektu a nebo, že Re.search() či Re.match() neakceptuje null, proto jsem to nechal tak jak to bylo v původním kódu a neprepisoval to.

2017-02-08 19:58 UTC, ExSport commented on resources/lib/sutils.py
>                  tvid = None
Btw. jsem četl někde že porovnání null objektu se dělá přes IS/IS NOT a pro true/false IF/IF NOT.
Klidně přepisu.

2017-02-08 20:00 UTC, ExSport commented on resources/lib/sutils.py
> +                        re.match('^$|^[?0]$', params['imdb']) is None):
Viz mé vysvětlení výše proč závorky a if null x true/false. Klidně přepisu.

2017-02-08 20:04 UTC, ExSport commented
@Lubo Porad jakou máš představu ohledně toho XML parsování, nasměruj mě a já to zkusím přepsat.
Díky

2017-02-08 22:19 UTC, Lubo commented on resources/lib/sutils.py
> +                    id + '&language=all'))
Vec je, ze tu ale nemusis ukoncit riadok lomitkom. Najlepsi practice je, nedavat veci tam, kde su zbytocne.

2017-02-08 22:27 UTC, Lubo commented on resources/lib/sutils.py
> +                tvid = re.search('<id>(\d+)</id>', data).group(1)
Ze uz nejaky kod uz bol neznamena, ze je korektny. Treba sa preto vzdy nad tym zamysliet. Parsovanie XML nie je python-specific vec, takze to celkom neberiem. Ak chces vediet o parsovani XML v pythone viac, prozri sa [sem](https://docs.python.org/2/library/xml.etree.elementtree.html).

2017-02-08 22:30 UTC, Lubo commented on resources/lib/sutils.py
>                  tvid = None
1. Treba si lepsie precitat dokumentaciu
2. To je sice pravda, ale `None` je v pythone falsy object, preto to nemusis robit.

2017-02-08 22:33 UTC, lubo commented
@ExSport Do komentaru som ti dal link na clanok z dokumentacie ohladom parsovania XML.

2017-02-09 17:47 UTC, ExSport commented
@Lubo Dik za odkaz ohledne XML parsingu.
Zatim jsem prepsal zbytek tebou zmineny, XML cast jak bude zase cas...

2017-02-09 22:00 UTC, lubo requested changes
Teraz som uz ovela spokojnejsi s tym kodom. Este chyba ten XML parsing. Inac 175-179 a 198-202 vyzeraju rovnako. Mozno by nebolo odveci spravit preto nejaku helper funkciu.

2017-02-10 10:56 UTC, ExSport commented
Opravoval jsem kod a vylepsoval detekci, neprepisoval jsem cely puvodni kod, takze ty dve stejne casti neni ma prace:)
Chtel jsem provest rychlou opravu at se zbytecne lidem nevygeneruji nevalidni NFO soubory/odkazy, ktere pak jen tezko opravi (ve vetsim poctu), tak z meho pohledu slo o rychly fix a ne prepisovani celeho kodu, protoze neni schick.
Pokud s tim nemas problem, tak to please mergni pro ostatni a ja snad behem tydne, dvou prepisu tu XML cast. Driv to urcite nestihnu, tak at lidi zbytecne necekaji, pripadne kdyby se toho nekdo zhostil driv... 👍

2017-02-11 13:37 UTC, Lubo commented
Dobre. Normalne by som toto nespravil, ale ak to ludom nefunguje a ty proste nemas momentalne viacej casu, tak musime siahnut po kompromisnom riesenie.

2017-02-11 20:53 UTC, ExSport commented
CodeClimatu se nelíbí délka řádku o 1 znak a když jsem na tvůj popud odstranil ty závorky když to bylo na dva řádky, nikdy se mi to nezkompilovalo ať už plus byl na začátku či na konci, takže mě napadlo už jen lomítko na konci ale to prý už není doporučováno/deprecated v novějších verzích Pythonu, pokud si pamatuji dobře. Proto jsem to dal na jeden řádek protože jinde jsem se dočetl, že ikdyz Climate řve, tak do 120 či kolika znaků je to stále ok.
Btw. ten kód funguje, jen pro některé tituly vytvoří link na něco jiné nebo vytvoří neexistující link, či vytvoří nfo file ikdyz neexistuje žádný validní link.
U seriálů navíc používal zbytečně bbaron.sk web. Nyní by odkaz na thetvdb měl být přesnější, je totiž generovan z imdb id a pokud se nenajde, zkusí to přes název bez roku (thetvdb nepodporuje rok takže s ním většinou nic nenajde), následně se pokusí i s rokem. No a hledání ještě upřesňuje přes Lang=CS a když nic nenajde, tak zkusí ještě speciální Lang=all, který hledá napříč jazyky (jen pro některé tituly pod all nebyla český titul, ale pod Lang=CS to bylo...Proto první preferuje lang=cs).
A ještě jsem opravil bug, že pokud se nenalezl thetvdb link, pak se vůbec negeneroval nfo file ani když existoval ČSFD či imdb link.
Na to XML parsování ale časem ještě mrknu, aspoň se něco nové naučím.
Díky

2017-02-11 21:42 UTC, Lubo commented
Pockaj, aky plus ? V tych if statementoch nie su ziadne plusy... Ale nevedel som, ze tie statementy su pridlhe, v tom pripade je to OK a mal si mi to povedat. V kazdom pripade, Code Climate tu mame na enforcement nasej konvencie, cize ak reve, nie je to OK.

Ak to XML parsovanie teraz nevyriesis, tak ja to stale mozem mergnut s tym, ze ked to nebude fungovat, tak budeme prstom ukazovat na teba.

2017-02-11 21:51 UTC, ExSport commented
Ok sorry ty plusy bylo něco jiné co jsem vyřešil:)
Tu mě to asi nebralo NOT na konci ani na začátku řádku a bez těch původních závorek to házelo chybu při kompilaci, jestli si pamatuji dobře.
No sice jsem ten původní XML parsing nepsal já, ale klidně ukaž na mě...dokud to neprepisu tak se vymluvim na původního autora 😄
Díky.

2017-02-11 21:53 UTC, Lubo commented
Slusnost kaze, ze kto sa toho posledny chytal, ten je za to zodpovedny :) Pridaj tam tie zatvorky a bude to na teraz stacit.

2017-02-11 21:56 UTC, ExSport commented
Ok vrátím je tam ale ne dřív než v pondělí asi. Z mobilu to nedám:)

2017-02-13 17:58 UTC, lubo approved these changes

2017-02-13 17:59 UTC, merged

2017-02-20 09:43 UTC, ExSport commented
Dik za merge