Prepsan PRINT na UTIL.Info/Debug/Error z duvodu generovani vyjimky
kodi-czsk/plugin.video.sosac.ph pull request #84
Opened 2016-10-12 09:49 UTC by ExSport

https://bugs.python.org/issue706263

2016-10-12 19:01 UTC, lubo requested changes
Vyzera to byt fajn, len zmen prosim commit messages. Su pridlhe. Vid. http://chris.beams.io/posts/git-commit/.

2016-10-12 20:19 UTC, ExSport commented
@Lubo Zítra provedu. Z mobilu nejde online editovat commit messages, jen pull subject a body :(

2016-10-13 14:21 UTC, ExSport commented
@Lubo Byl to boj, ale snad se podarilo (amend v TortoiseGit je brnkacka, ale editovat jiny nez posledni comment pres rebase je o hubu:-))

2016-10-13 14:40 UTC, lubo approved these changes

2016-10-13 14:41 UTC, Lubo commented
Pocul si niekedy o filter-branch ? Nevadi, dobra praca.

2016-10-13 14:42 UTC, merged

2016-10-13 15:10 UTC, ExSport commented
@Lubo Jo, ted:-) Kazdopadne v TortoiseGit GUI jsem to nenasel, takze asi jedine command line.
Mrknu, dik (google radil pouze a jen rebase, viz napr. [link](https://help.github.com/articles/changing-a-commit-message/)