Zmenen zpusob nacitani kategorie "Movies - Recently added"
kodi-czsk/plugin.video.sosac.ph pull request #85
Opened 2016-10-12 09:51 UTC by ExSport

- Misto parsovani HTML stranky se nove nacita primo z XML (rychlejsi)
- Opraveno nacitani poslednich 200 polozek misto puvodnich 45
- Zobrazuje postery u videa
- Zobrazuje kvalitu videa

2016-10-13 15:45 UTC, ExSport commented
@Lubo @lzoubek Neco jeste extra potreba dodelat, aby to bylo mergnuto? Dik

2016-10-14 15:34 UTC, E000001 commented
Asi by bylo jeste dobry upravit addon.xml a history.txt

2016-10-15 16:57 UTC, lubo requested changes

2016-10-15 16:57 UTC, Lubo commented on resources/lib/sosac.py
> +                pass
Zda sa mi to, alebo mame tento isty kod vo viacerych metodach ? Nie je dobre mat duplicitny kod, chcelo to ho mat len na jednom mieste.

2016-10-15 16:57 UTC, Lubo commented
@E000001 A co presne by si do nich chcel pridat ?

2016-10-15 17:28 UTC, ExSport commented on resources/lib/sosac.py
> +                pass
@Lubo Částečně.
Kompletně jsem přepsal **list_movie_recently_added** ve stejném duchu jak jsem upravil i **list_xml_letter**
Fragmenty kódu jsou tam tedy podobné.
To chceš na ten kousek podobného kódu separátní fci či?

2016-10-19 16:15 UTC, E000001 commented
@Lubo Minimálně navýšit verzi, aby kodi poznalo že došlo k updatu a do history nějaký povídání o změnách :)

2016-10-19 16:21 UTC, Lubo commented
@E000001 To v tomto PR nema co hladat.

2016-11-01 18:04 UTC, Lubo commented on resources/lib/sosac.py
> +                pass
Ano, jednoznacne.

2016-12-25 01:56 UTC, Lubo commented
@ExSport Nejaky update ?

2017-01-10 17:43 UTC, closed without merging

2017-01-11 13:05 UTC, ExSport commented
Toto uz je asi pase, po prechodu na JSON 👍