Zobrazuje kvalitu u filmu + opravuje nektere chybejici polozky s diakritikou
kodi-czsk/plugin.video.sosac.ph pull request #86
Opened 2016-10-12 10:09 UTC by ExSport

Inspirace z: https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/77

2016-10-12 21:50 UTC, lubo requested changes
Znova, pridlhy commit message.

2016-10-12 21:50 UTC, Lubo commented on resources/lib/sosac.py
> +                add2library = '%s (%s)' % (title, film.findtext('rokvydani'))
`item['title']` aj `add2library` maju spolocny zaklad. Preco ho nezformulujes len raz ?

2016-10-12 21:50 UTC, Lubo commented on resources/lib/sosac.py
> +                item['name'] = item['title']
Toto mozes spojit s riadkom vyssie, kde inicializujes `item['title']`. Nech je na jednom mieste vydiet, ze kam sa vsade sa pcha rovnaka hodnota.

2016-10-13 15:03 UTC, ExSport commented
@Lubo Prepsano. Snad muze byt takto.

2016-10-14 00:57 UTC, lubo requested changes

2016-10-14 00:57 UTC, Lubo commented on resources/lib/sosac.py
> +                item['title'] = '%s - %s' % (basetitle, film.findtext('kvalita'))
Nechcel by si este prevadzat kvalitu do upper case ? Lebo napr. hd nie je skratka od High-definition, ale HD je.

2016-10-14 14:47 UTC, ExSport commented on resources/lib/sosac.py
> +                item['title'] = '%s - %s' % (basetitle, film.findtext('kvalita'))
Hotovo

2016-10-15 16:48 UTC, lubo approved these changes

2016-10-15 16:48 UTC, merged